experimenter: HHC
prep_choices: [Left optic lobe, Right optic lobe]
driver_choices: [Tm3 (R13E12-Gal4), Tm3 (R13E12-LexA)]
indicator_choices: [UAS-GCaMP6f, UAS-TNT, LexAOp-GCaMP6f, LexAOp-TNT]


rig_config:
  Bruker_LeftScreen:
    data_directory: E:/Heather
    screen_center: [130,120]
    rig: Bruker